swagger: '2.0'
info:
  title: OPs API
  version: '1.0'
basePath: /v1.0
paths:
  /items:
    get:
      responses:
        '200':
          description: Fetch a list of items
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
  /status:
    get:
      responses:
        '200':
          description: SLTC Status
          schema:
            type: object
            items:
              $ref: '#/definitions/Status'
definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Status:
    type: object
    properties:
      hb:
        type: string
        format: date-time
      tmhp_up:
        type: boolean
      alerts:
        type: array
        items:
          properties:
            mds_batches:
              type: array
              items:
                $ref: '#/definitions/Batches'
            pbj_batches:
              type: array
              items:
                $ref: '#/definitions/Batches'
            overdue_reports:
              type: array
              items:
                type: object
                properties:
                  uid:
                    type: integer
                    format: int64
                  fac_uid:
                    type: integer
                    format: int64
                  report_type:
                    type: string
                  status:
                    type: string
                  upload_date:
                    type: string
                    format: date-time
            cfs_forms:
              type: array
              items:
                type: object
                properties:
                  uid:
                    type: integer
                    format: int64
                  fac_uid:
                    type: integer
                    format: int64
                  form_type:
                    type: string
                  status:
                    type: string
                  upload_date:
                    type: string
                    format: date-time
  Batches:
    type: object
    properties:
      uid:
        type: integer
        format: int64
      fac_uid:
        type: integer
        format: int64
      filename:
        type: string
      upload_date:
        type: string
        format: date-time
      status:
        type: string
